import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footerdemo from '../components/ui/footer-section.jsx';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({}) {
    return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <header className="flex items-center justify-between p-6">
        <h1 className="text-2xl font-bold text-gray-900">Raiyan Mahfuz<span className="text-purple-500">.</span></h1>

        <nav className="bg-white px-6 py-2 rounded-full shadow-md">
            <ul className="flex space-x-6 text-gray-700">
                <li><a href="#" className="hover:text-purple-500">Home</a></li>
                <li><a href="" className="hover:text-purple-500">About</a></li>
                <li><a href="#" className="hover:text-purple-500">Skills</a></li>
                <li><a href="#" className="hover:text-purple-500">Projects</a></li>
                <li><a href="#" className="hover:text-purple-500">Contact</a></li>
            </ul>
        </nav>

        <div className="flex items-center space-x-4">
            <a href="#"
               className="border border-gray-300 dark:border-gray-600 px-4 py-2 rounded-full flex items-center space-x-2 hover:bg-gray-100 dark:hover:bg-gray-700">
                <span>Contact</span>
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24"
                     stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path>
                </svg>
            </a>
        </div>
    </header>
    <main>
        <div className="flex justify-between items-center py-50 p-5">
            <nav className="w-1/2 p-5">
                <nav className="text-center text-4xl font-bold text-gray-400">Hello I`m</nav>
                <nav className="text-center text-5xl font-bold py-2">Raiyan Mahfuz</nav>
                <nav className="text-center text-5xl font-bold text-gray-400 py-2">Frontend Developer</nav>
                <nav className="flex justiy-between justify-center space-x-3 py-4">
                    <button
                        type="button"
                        className="w-40 text-white bg-black border-3  font-medium rounded-full text-sm px-8 py-4 text-center mb-2 transition duration-300 hover:shadow-md hover:bg-neutral-700">
                        <a href="/MahfuzRaiyan_Lebenslauf.pdf" download>Download CV</a>
                    </button>
                    <button
                        type="button"
                        className="w-40 text-white bg-sky-600 border-3 border-sky font-medium rounded-full text-sm px-8 py-4 text-center mb-2 transition duration-300 hover:shadow-md hover:bg-sky-800">
                        Contact info
                    </button>
                </nav>
            </nav>
        </div>

        <div>
            <h2 className="text-center text-sky-600 font-bold border-b-2 border-blue-500 border-transparent pt-40 text-2xl"
                id="about">About</h2>
            <div className="flex justify-between items-center py-50 p-5">
                <nav className="w-1/2 p-5">
                    <img
                        src="https://via.placeholder.com/600x600"
                        alt="Placeholder"
                        className="mx-auto rounded-lg shadow-lg"
                    />
                </nav>
            </div>
        </div>
    </main>
    <Footerdemo />
    </body>
    </html>
    );
}
