import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <header className="flex justify-between items-center px-8 py-6 text-blue-500 text-2xl"
            style={{
                backgroundColor: "white",
            }}
    >
        <h1 className="text-2xl font-semibold">Raiyan Mahfuz</h1>
        <nav>
            <ul className="flex space-x-6">
                <li>
                    <a href="/home/" className="border-b-2 border-transparent hover:border-blue-500">
                        Home
                    </a>
                </li>
                <li>
                    <a href="/about/" className="border-b-2 border-transparent hover:border-blue-500">
                        About
                    </a>
                </li>
                <li>
                    <a href="/skills/" className="border-b-2 border-transparent hover:border-blue-500">
                        Skills
                    </a>
                </li>
                <li>
                    <a href="/projects/" className="border-b-2 border-transparent hover:border-blue-500">
                        Projects
                    </a>
                </li>
                <li>
                    <a href="/contact/" className="border-b-2 border-transparent hover:border-blue-500">
                        Contact
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    <main>

        <div className="flex justify-between items-center py-50 p-5">
            <nav className="w-1/2 p-5">
                <nav className="text-center text-4xl font-bold text-gray-400">Hello I'm</nav>
                <nav className="text-center text-5xl font-bold py-2">Raiyan Mahfuz</nav>
                <nav className="text-center text-5xl font-bold text-gray-400 py-2">Frontend Developer</nav>
                <nav className="flex justiy-between justify-center space-x-3 py-4">
                    <button
                        type="button"
                        className="w-40 text-white bg-black border-3  font-medium rounded-full text-sm px-8 py-4 text-center mb-2 transition duration-300 hover:shadow-md hover:bg-neutral-700">
                        <a href="/MahfuzRaiyan_Lebenslauf.pdf" download>Download CV</a>
                    </button>
                    <button
                        type="button"
                        className="w-40 text-white bg-sky-600 border-3 border-sky font-medium rounded-full text-sm px-8 py-4 text-center mb-2 transition duration-300 hover:shadow-md hover:bg-sky-800">
                        Contact info
                    </button>
                </nav>
            </nav>
        </div>

        <div>
            <h2 className="text-center text-sky-600 font-bold border-b-2 border-blue-500 border-transparent pt-40 text-2xl">About</h2>
        </div>

    </main>
    <footer className="bg-sky-500 text-white text-center py-6 mt-12 font-bold">
        <div className="container mx-auto">
            <div className="flex justify-center space-x-6 mb-4">
                <a href="https://linkedin.com/in/deinprofil" target="_blank" rel="noopener noreferrer">
                    LinkedIn
                </a>
                <a href="https://github.com/deinprofil" target="_blank" rel="noopener noreferrer">
                    GitHub
                </a>
                <a href="mailto:sadgidmahfuz@email.com">sadgidmahfuz@email.com</a>
            </div>
            <p className="text-sm">© 2025 Raiyan Mahfuz. Alle Rechte vorbehalten.</p>
        </div>
    </footer>
    </body>
    </html>
  );
}
